UPDATE "prospectsPotentiels" SET "reviewCount" = 4, rating = 4.7 WHERE name = 'Bœuf & Cow';
UPDATE "prospectsPotentiels" SET "reviewCount" = 4, rating = 4.7 WHERE name = 'Le Bouchon du Vaugueux';
UPDATE "prospectsPotentiels" SET "reviewCount" = 4, rating = 4.8 WHERE name = 'Balthazar';
UPDATE "prospectsPotentiels" SET "reviewCount" = 4, rating = 4.9 WHERE name = 'AUGIA';
UPDATE "prospectsPotentiels" SET "reviewCount" = 4, rating = 4.8 WHERE name = 'Le Maharajah';
UPDATE "prospectsPotentiels" SET "reviewCount" = 4, rating = 4.9 WHERE name = 'Bistrot L''échoppe';
UPDATE "prospectsPotentiels" SET "reviewCount" = 5, rating = 5.0 WHERE name = 'Amalia';
UPDATE "prospectsPotentiels" SET "reviewCount" = 4, rating = 4.9 WHERE name = 'Et Si & Cie';
UPDATE "prospectsPotentiels" SET "reviewCount" = 4, rating = 4.9 WHERE name = 'Pasta i Basta - Caen';
UPDATE "prospectsPotentiels" SET "reviewCount" = 4, rating = 4.6 WHERE name = 'Monsieur Louis';
UPDATE "prospectsPotentiels" SET "reviewCount" = 4, rating = 4.9 WHERE name = 'Une Cuillère Carrée';
UPDATE "prospectsPotentiels" SET "reviewCount" = 4, rating = 4.7 WHERE name = 'Bayla';
UPDATE "prospectsPotentiels" SET "reviewCount" = 4, rating = 4.8 WHERE name = 'Les Papilles';
UPDATE "prospectsPotentiels" SET "reviewCount" = 4, rating = 4.5 WHERE name = 'Le Bistronome';
UPDATE "prospectsPotentiels" SET "reviewCount" = 4, rating = 4.9 WHERE name = 'Sequence Restaurant';
UPDATE "prospectsPotentiels" SET "reviewCount" = 4, rating = 4.8 WHERE name = 'L’Étoile Caen';
UPDATE "prospectsPotentiels" SET "reviewCount" = 4, rating = 4.7 WHERE name = 'La Casinière';
UPDATE "prospectsPotentiels" SET "reviewCount" = 4, rating = 4.8 WHERE name = 'Le Potager';
UPDATE "prospectsPotentiels" SET "reviewCount" = 4, rating = 4.9 WHERE name = 'Moments Restaurant & Bar à manger';
UPDATE "prospectsPotentiels" SET "reviewCount" = 4, rating = 4.8 WHERE name = 'Mookys';
UPDATE "prospectsPotentiels" SET "reviewCount" = 4, rating = 4.8 WHERE name = 'Les Dunes';
UPDATE "prospectsPotentiels" SET "reviewCount" = 4, rating = 4.6 WHERE name = 'L''Hydropathe';
UPDATE "prospectsPotentiels" SET "reviewCount" = 4, rating = 4.7 WHERE name = 'Restaurant Guinguette';
UPDATE "prospectsPotentiels" SET "reviewCount" = 4, rating = 4.9 WHERE name = 'Indigène';
UPDATE "prospectsPotentiels" SET "reviewCount" = 4, rating = 4.6 WHERE name = 'Moon & Sons';
UPDATE "prospectsPotentiels" SET "reviewCount" = 4, rating = 4.8 WHERE name = 'Krousty Sabaidi - Caen';
UPDATE "prospectsPotentiels" SET "reviewCount" = 4, rating = 4.9 WHERE name = 'Chez Rose';
UPDATE "prospectsPotentiels" SET "reviewCount" = 4, rating = 4.8 WHERE name = 'Sacrée Mathilde';
UPDATE "prospectsPotentiels" SET "reviewCount" = 4, rating = 4.9 WHERE name = 'Simplexité';
UPDATE "prospectsPotentiels" SET "reviewCount" = 4, rating = 4.6 WHERE name = 'Le Pavillon Caen';
UPDATE "prospectsPotentiels" SET "reviewCount" = 4, rating = 4.8 WHERE name = 'Mian Mian';
UPDATE "prospectsPotentiels" SET "reviewCount" = 4, rating = 4.7 WHERE name = 'La Tomette';
UPDATE "prospectsPotentiels" SET "reviewCount" = 4, rating = 4.8 WHERE name = 'Pizzeria Canaglia Caen';
UPDATE "prospectsPotentiels" SET "reviewCount" = 4, rating = 4.6 WHERE name = 'La Trattoria';
UPDATE "prospectsPotentiels" SET "reviewCount" = 4, rating = 4.7 WHERE name = 'La Veranda';
UPDATE "prospectsPotentiels" SET "reviewCount" = 4, rating = 4.6 WHERE name = 'Tartines et Gourmandises';
UPDATE "prospectsPotentiels" SET "reviewCount" = 4, rating = 4.8 WHERE name = 'Le Coeur Gourmand';
UPDATE "prospectsPotentiels" SET "reviewCount" = 4, rating = 4.7 WHERE name = 'Pain vivant';
UPDATE "prospectsPotentiels" SET "reviewCount" = 4, rating = 4.7 WHERE name = 'Boulanger Pâtissier "Les Pains de Gabin"';
UPDATE "prospectsPotentiels" SET "reviewCount" = 4, rating = 4.3 WHERE name = 'Boulanger Pâtissier "Le Moulin des Pierres Caen""';
UPDATE "prospectsPotentiels" SET "reviewCount" = 4, rating = 4.3 WHERE name = 'La Brioche Chaude';
UPDATE "prospectsPotentiels" SET "reviewCount" = 4, rating = 4.8 WHERE name = 'La rose de Vaucelles';
UPDATE "prospectsPotentiels" SET "reviewCount" = 4, rating = 4.5 WHERE name = 'Talemelerie Guillaume';
UPDATE "prospectsPotentiels" SET "reviewCount" = 4, rating = 4.7 WHERE name = 'Boulangerie Pâtisserie "Calou"';
UPDATE "prospectsPotentiels" SET "reviewCount" = 4, rating = 4.5 WHERE name = 'Graines De Copains';
UPDATE "prospectsPotentiels" SET "reviewCount" = 4, rating = 4.5 WHERE name = 'Le P''tit Chou';
UPDATE "prospectsPotentiels" SET "reviewCount" = 4, rating = 4.2 WHERE name = 'Maison Roney';
UPDATE "prospectsPotentiels" SET "reviewCount" = 4, rating = 4.4 WHERE name = 'Maison Vivien';
UPDATE "prospectsPotentiels" SET "reviewCount" = 4, rating = 4.6 WHERE name = 'L''épi de venoix';
UPDATE "prospectsPotentiels" SET "reviewCount" = 4, rating = 4.8 WHERE name = 'Boulangerie Pâtisserie Persigny';
UPDATE "prospectsPotentiels" SET "reviewCount" = 4, rating = 4.5 WHERE name = 'Boulanger Pâtissier "Aux Normandises"';
UPDATE "prospectsPotentiels" SET "reviewCount" = 4, rating = 4.4 WHERE name = 'Paintati & Paintata';
UPDATE "prospectsPotentiels" SET "reviewCount" = 4, rating = 4.4 WHERE name = 'La Mie Paulette';
UPDATE "prospectsPotentiels" SET "reviewCount" = 4, rating = 4.3 WHERE name = 'Boulangerie Banette Saveurs';
UPDATE "prospectsPotentiels" SET "reviewCount" = 4, rating = 4.6 WHERE name = 'L''Annexe';
UPDATE "prospectsPotentiels" SET "reviewCount" = 4, rating = 4.7 WHERE name = 'Maison Cookie';
UPDATE "prospectsPotentiels" SET "reviewCount" = 4, rating = 4.5 WHERE name = 'Pâtisserie Alban Guilmet';
UPDATE "prospectsPotentiels" SET "reviewCount" = 4, rating = 4.3 WHERE name = 'Bon''blé';
UPDATE "prospectsPotentiels" SET "reviewCount" = 4, rating = 4.3 WHERE name = 'Carrément Gourmand';
UPDATE "prospectsPotentiels" SET "reviewCount" = 4, rating = 4.4 WHERE name = 'La kaz a pains';
UPDATE "prospectsPotentiels" SET "reviewCount" = 4, rating = 4.6 WHERE name = 'Alban Guilmet';
UPDATE "prospectsPotentiels" SET "reviewCount" = 4, rating = 4.0 WHERE name = 'Au fournil de l''Hippodrome';
UPDATE "prospectsPotentiels" SET "reviewCount" = 4, rating = 4.0 WHERE name = 'Mariatte et Fils Boulangerie';
UPDATE "prospectsPotentiels" SET "reviewCount" = 4, rating = 4.2 WHERE name = 'Boulangerie Feuillette';
UPDATE "prospectsPotentiels" SET "reviewCount" = 4, rating = 4.2 WHERE name = 'Aux Délices d’Édimbourg';
UPDATE "prospectsPotentiels" SET "reviewCount" = 4, rating = 4.4 WHERE name = 'La Mie Câline Caen';
UPDATE "prospectsPotentiels" SET "reviewCount" = 4, rating = 4.7 WHERE name = 'Fournil bio Mie figue - Mie raisin';
UPDATE "prospectsPotentiels" SET "reviewCount" = 3, rating = 3.9 WHERE name = 'Boulangerie Pâtisserie traditions et gourmandises';
UPDATE "prospectsPotentiels" SET "reviewCount" = 4, rating = 4.0 WHERE name = 'Grain de blé';
UPDATE "prospectsPotentiels" SET "reviewCount" = 4, rating = 4.1 WHERE name = 'Coiff&Co - Coiffeur Herouville Saint Clair';
UPDATE "prospectsPotentiels" SET "reviewCount" = 4, rating = 4.8 WHERE name = 'Esma';
UPDATE "prospectsPotentiels" SET "reviewCount" = 4, rating = 4.9 WHERE name = 'Octobre Coiffure & Barbier Caen';
UPDATE "prospectsPotentiels" SET "reviewCount" = 4, rating = 4.9 WHERE name = 'El''oz coiffure';
UPDATE "prospectsPotentiels" SET "reviewCount" = 4, rating = 4.8 WHERE name = 'Salon SoHo';
UPDATE "prospectsPotentiels" SET "reviewCount" = 4, rating = 4.6 WHERE name = 'Studio coiffure';
UPDATE "prospectsPotentiels" SET "reviewCount" = 4, rating = 4.8 WHERE name = 'The Workshop Coiffure';
UPDATE "prospectsPotentiels" SET "reviewCount" = 4, rating = 4.7 WHERE name = 'Chez Léa';
UPDATE "prospectsPotentiels" SET "reviewCount" = 5, rating = 5.0 WHERE name = 'Mood Coiffure Caen';
UPDATE "prospectsPotentiels" SET "reviewCount" = 4, rating = 4.8 WHERE name = 'Moi d''abord - Coiffeur Caen';
UPDATE "prospectsPotentiels" SET "reviewCount" = 4, rating = 4.7 WHERE name = 'Stil''ling Coiffure';
UPDATE "prospectsPotentiels" SET "reviewCount" = 5, rating = 5.0 WHERE name = 'L''APPART C';
UPDATE "prospectsPotentiels" SET "reviewCount" = 5, rating = 5.0 WHERE name = 'Original Box Coiffure';
UPDATE "prospectsPotentiels" SET "reviewCount" = 4, rating = 4.9 WHERE name = 'Anaïs Ametller';
UPDATE "prospectsPotentiels" SET "reviewCount" = 4, rating = 4.9 WHERE name = '3ème Art';
UPDATE "prospectsPotentiels" SET "reviewCount" = 4, rating = 4.6 WHERE name = 'Kokliko Koiffure';
UPDATE "prospectsPotentiels" SET "reviewCount" = 4, rating = 4.6 WHERE name = 'Coiffeur chez Max GOLD CAEN';
UPDATE "prospectsPotentiels" SET "reviewCount" = 4, rating = 4.9 WHERE name = 'Monsieur et ses Ateliers';
UPDATE "prospectsPotentiels" SET "reviewCount" = 4, rating = 4.6 WHERE name = 'Addict Paris Coiffure';
UPDATE "prospectsPotentiels" SET "reviewCount" = 4, rating = 4.7 WHERE name = 'Harry Le Coiffeur et Barbier';
UPDATE "prospectsPotentiels" SET "reviewCount" = 4, rating = 4.8 WHERE name = 'Miss hair coiffure esthétique expert Relooking';
UPDATE "prospectsPotentiels" SET "reviewCount" = 4, rating = 4.4 WHERE name = 'Franck Provost - Coiffeur Herouville Saint Clair';
UPDATE "prospectsPotentiels" SET "reviewCount" = 5, rating = 5.0 WHERE name = 'LC Barber-shop Château';
UPDATE "prospectsPotentiels" SET "reviewCount" = 4, rating = 4.9 WHERE name = 'Synthèse Coiffure';
UPDATE "prospectsPotentiels" SET "reviewCount" = 4, rating = 4.5 WHERE name = 'Joakim coiffeur barbier';
UPDATE "prospectsPotentiels" SET "reviewCount" = 4, rating = 4.6 WHERE name = 'Coiffeur chez Max CAEN VENOIX';
UPDATE "prospectsPotentiels" SET "reviewCount" = 5, rating = 5.0 WHERE name = 'Salon Divin';
UPDATE "prospectsPotentiels" SET "reviewCount" = 5, rating = 5.0 WHERE name = 'KB coiffure';
UPDATE "prospectsPotentiels" SET "reviewCount" = 4, rating = 4.9 WHERE name = 'Cynthia B';
UPDATE "prospectsPotentiels" SET "reviewCount" = 4, rating = 4.7 WHERE name = 'Salon 49';
UPDATE "prospectsPotentiels" SET "reviewCount" = 4, rating = 4.8 WHERE name = 'Salon de Beauté - Emmanuel Touzé - Coiffeur - Visagiste - Esthétique - Coloriste - Soins - Coiffure mariage - Caen';
UPDATE "prospectsPotentiels" SET "reviewCount" = 4, rating = 4.8 WHERE name = 'VIP COIFFEUR';
UPDATE "prospectsPotentiels" SET "reviewCount" = 4, rating = 4.9 WHERE name = 'De Mèche Avec Moi - Coiffeur Végétal et Ecoresponsable';
UPDATE "prospectsPotentiels" SET "reviewCount" = 4, rating = 4.9 WHERE name = 'Homme a Part';
UPDATE "prospectsPotentiels" SET "reviewCount" = 5, rating = 5.0 WHERE name = 'Maysca';
UPDATE "prospectsPotentiels" SET "reviewCount" = 4, rating = 4.8 WHERE name = 'Relook coiffure by Bérangère';
UPDATE "prospectsPotentiels" SET "reviewCount" = 4, rating = 4.8 WHERE name = 'Pplomberie';
UPDATE "prospectsPotentiels" SET "reviewCount" = 4, rating = 4.9 WHERE name = 'LS Service Plombier Chauffage Calvados';
UPDATE "prospectsPotentiels" SET "reviewCount" = 5, rating = 5.0 WHERE name = 'plombier chauffagiste';
UPDATE "prospectsPotentiels" SET "reviewCount" = 4, rating = 4.9 WHERE name = 'AJ Plomberie Allan Jouenne';
UPDATE "prospectsPotentiels" SET "reviewCount" = 4, rating = 4.6 WHERE name = 'ADR Allo Dépannage Rapide';
UPDATE "prospectsPotentiels" SET "reviewCount" = 5, rating = 5.0 WHERE name = 'Plomberie MESLIN';
UPDATE "prospectsPotentiels" SET "reviewCount" = 4, rating = 4.8 WHERE name = 'SL2A Plomberie Chauffage Climatisation Pompe à chaleur';
UPDATE "prospectsPotentiels" SET "reviewCount" = 3, rating = 3.5 WHERE name = 'Stéphane Mottay - Plombier CAEN - Chauffagiste Caen - Dépannage Urgent Caen';
UPDATE "prospectsPotentiels" SET "reviewCount" = 5, rating = 5.0 WHERE name = 'AJBL';
UPDATE "prospectsPotentiels" SET "reviewCount" = 5, rating = 5.0 WHERE name = 'aqualanplomberie';
UPDATE "prospectsPotentiels" SET "reviewCount" = 5, rating = 5.0 WHERE name = 'A&M PLOMBIER14';
UPDATE "prospectsPotentiels" SET "reviewCount" = 5, rating = 5.0 WHERE name = 'BEDEAU Plomberie Chauffage Caen';
UPDATE "prospectsPotentiels" SET "reviewCount" = 3, rating = 3.4 WHERE name = 'PIQUOT';
UPDATE "prospectsPotentiels" SET "reviewCount" = 0, rating = 0.0 WHERE name = 'AAZ Dépannages';
UPDATE "prospectsPotentiels" SET "reviewCount" = 5, rating = 5.0 WHERE name = 'Balmer travaux et services';
UPDATE "prospectsPotentiels" SET "reviewCount" = 4, rating = 4.5 WHERE name = 'NVAIR Verdier Nicolas';
UPDATE "prospectsPotentiels" SET "reviewCount" = 4, rating = 4.3 WHERE name = 'H2O Factory';
UPDATE "prospectsPotentiels" SET "reviewCount" = 5, rating = 5.0 WHERE name = 'RK Plomberie';
UPDATE "prospectsPotentiels" SET "reviewCount" = 5, rating = 5.0 WHERE name = 'Arli Plomberie chauffage rénovation';
UPDATE "prospectsPotentiels" SET "reviewCount" = 4, rating = 4.5 WHERE name = 'LARCHER Services / Installation-Entretien-Dépannage Plomberie - Chauffage - Climatisation - Salle de bain - Cuisine/ CAEN';
UPDATE "prospectsPotentiels" SET "reviewCount" = 4, rating = 4.8 WHERE name = 'Thalea';
UPDATE "prospectsPotentiels" SET "reviewCount" = 3, rating = 3.5 WHERE name = 'Dufresne Bernard';
UPDATE "prospectsPotentiels" SET "reviewCount" = 2, rating = 2.0 WHERE name = 'Plombier Chauffagiste Caen Proxiserve';
UPDATE "prospectsPotentiels" SET "reviewCount" = 4, rating = 4.7 WHERE name = 'ARF - Recherche de fuite et détection de réseaux';
UPDATE "prospectsPotentiels" SET "reviewCount" = 4, rating = 4.9 WHERE name = 'SARL DELORYS';
UPDATE "prospectsPotentiels" SET "reviewCount" = 5, rating = 5.0 WHERE name = 'SARL TARDIF PLOMBERIE';
UPDATE "prospectsPotentiels" SET "reviewCount" = 3, rating = 3.7 WHERE name = 'Entreprise Lezoray';
UPDATE "prospectsPotentiels" SET "reviewCount" = 5, rating = 5.0 WHERE name = 'DBRL Plomberie - Chauffage - Dépannage';
UPDATE "prospectsPotentiels" SET "reviewCount" = 4, rating = 4.9 WHERE name = 'Michel David';
UPDATE "prospectsPotentiels" SET "reviewCount" = 4, rating = 4.6 WHERE name = 'JM Plomberie Chauffage';
UPDATE "prospectsPotentiels" SET "reviewCount" = 1, rating = 1.0 WHERE name = 'Caps';
UPDATE "prospectsPotentiels" SET "reviewCount" = 4, rating = 4.2 WHERE name = 'Renov''eau';
UPDATE "prospectsPotentiels" SET "reviewCount" = 4, rating = 4.5 WHERE name = 'ENR Ouest';
UPDATE "prospectsPotentiels" SET "reviewCount" = 4, rating = 4.8 WHERE name = 'JBP plomberie';
UPDATE "prospectsPotentiels" SET "reviewCount" = 4, rating = 4.3 WHERE name = 'Les Gars des Eaux';
UPDATE "prospectsPotentiels" SET "reviewCount" = 5, rating = 5.0 WHERE name = 'Electricien caen rapide';
UPDATE "prospectsPotentiels" SET "reviewCount" = 5, rating = 5.0 WHERE name = 'Électricien Le Petit Barbu';
UPDATE "prospectsPotentiels" SET "reviewCount" = 4, rating = 4.9 WHERE name = 'Electrique Cité';
UPDATE "prospectsPotentiels" SET "reviewCount" = 5, rating = 5.0 WHERE name = 'Cemtec dépannage';
UPDATE "prospectsPotentiels" SET "reviewCount" = 4, rating = 4.5 WHERE name = 'Thomasse Electricité';
UPDATE "prospectsPotentiels" SET "reviewCount" = 4, rating = 4.9 WHERE name = 'Briand Electricité | Électricien à Caen';
UPDATE "prospectsPotentiels" SET "reviewCount" = 4, rating = 4.8 WHERE name = 'Dumarais Électricité';
UPDATE "prospectsPotentiels" SET "reviewCount" = 5, rating = 5.0 WHERE name = 'HD Electricité | Electricien Caen';
UPDATE "prospectsPotentiels" SET "reviewCount" = 5, rating = 5.0 WHERE name = 'SCOP Poullain-SEPI';
UPDATE "prospectsPotentiels" SET "reviewCount" = 4, rating = 4.9 WHERE name = 'Adielec - Agence de Caen';
UPDATE "prospectsPotentiels" SET "reviewCount" = 4, rating = 4.9 WHERE name = 'Bs Rénovation';
UPDATE "prospectsPotentiels" SET "reviewCount" = 5, rating = 5.0 WHERE name = 'Jordan Electricité EURL';
UPDATE "prospectsPotentiels" SET "reviewCount" = 5, rating = 5.0 WHERE name = 'Daligault Electricité';
UPDATE "prospectsPotentiels" SET "reviewCount" = 5, rating = 5.0 WHERE name = 'Blot Électricité - Câbleur de tableau électrique';
UPDATE "prospectsPotentiels" SET "reviewCount" = 4, rating = 4.8 WHERE name = 'LEVIVIER ELEC';
UPDATE "prospectsPotentiels" SET "reviewCount" = 4, rating = 4.3 WHERE name = 'Serrure Elec Caen';
UPDATE "prospectsPotentiels" SET "reviewCount" = 5, rating = 5.0 WHERE name = 'ELECTRIKCAEN - Électricien Ouistreham, Caen Nord & Côte de Nacre';
UPDATE "prospectsPotentiels" SET "reviewCount" = 5, rating = 5.0 WHERE name = 'LUDOTECH';
UPDATE "prospectsPotentiels" SET "reviewCount" = 5, rating = 5.0 WHERE name = 'ALTER-ELEC';
UPDATE "prospectsPotentiels" SET "reviewCount" = 5, rating = 5.0 WHERE name = 'SPEED AND TOP - ELECTRICITE - CAEN';
UPDATE "prospectsPotentiels" SET "reviewCount" = 5, rating = 5.0 WHERE name = 'APLOMBELEC Plombier & Electricien';
UPDATE "prospectsPotentiels" SET "reviewCount" = 5, rating = 5.0 WHERE name = 'Naohme Électricien à Caen - Installation & Rénovation Électrique';
UPDATE "prospectsPotentiels" SET "reviewCount" = 4, rating = 4.8 WHERE name = 'DRD ELECTRICITE DOMOTIQUE';
UPDATE "prospectsPotentiels" SET "reviewCount" = 4, rating = 4.8 WHERE name = 'Connect''elec';
UPDATE "prospectsPotentiels" SET "reviewCount" = 3, rating = 3.3 WHERE name = 'Apluselec SAS';
UPDATE "prospectsPotentiels" SET "reviewCount" = 5, rating = 5.0 WHERE name = 'Aerd';
UPDATE "prospectsPotentiels" SET "reviewCount" = 5, rating = 5.0 WHERE name = 'L.j. Elec Sarl';
UPDATE "prospectsPotentiels" SET "reviewCount" = 4, rating = 4.9 WHERE name = 'Team''Elec';
UPDATE "prospectsPotentiels" SET "reviewCount" = 4, rating = 4.0 WHERE name = 'Mex Elec - électricien - électricité générale à Caen';
UPDATE "prospectsPotentiels" SET "reviewCount" = 5, rating = 5.0 WHERE name = 'ELNF';
UPDATE "prospectsPotentiels" SET "reviewCount" = 0, rating = 0.0 WHERE name = 'DUFRESNE-Electricien';
UPDATE "prospectsPotentiels" SET "reviewCount" = 5, rating = 5.0 WHERE name = 'IDED LOUIS LILIAN';
UPDATE "prospectsPotentiels" SET "reviewCount" = 5, rating = 5.0 WHERE name = 'Reno elec';
UPDATE "prospectsPotentiels" SET "reviewCount" = 4, rating = 4.4 WHERE name = 'Jacques Pierre SARL';
UPDATE "prospectsPotentiels" SET "reviewCount" = 4, rating = 4.6 WHERE name = 'Hector Couverture Normandie';
UPDATE "prospectsPotentiels" SET "reviewCount" = 5, rating = 5.0 WHERE name = 'Genel Couverture';
UPDATE "prospectsPotentiels" SET "reviewCount" = 4, rating = 4.8 WHERE name = 'La Maison Des Travaux';
UPDATE "prospectsPotentiels" SET "reviewCount" = 0, rating = 0.0 WHERE name = 'Artisan Normand';
UPDATE "prospectsPotentiels" SET "reviewCount" = 5, rating = 5.0 WHERE name = 'Ornata - Artisan, Spécialiste de la Rénovation';
UPDATE "prospectsPotentiels" SET "reviewCount" = 5, rating = 5.0 WHERE name = 'Jeff Rénovation';
UPDATE "prospectsPotentiels" SET "reviewCount" = 4, rating = 4.8 WHERE name = 'Kaly-T Bâtiment';
UPDATE "prospectsPotentiels" SET "reviewCount" = 5, rating = 5.0 WHERE name = 'ACTIV TRAVAUX - P2EP';
UPDATE "prospectsPotentiels" SET "reviewCount" = 4, rating = 4.9 WHERE name = 'NEW RENOVATION PROJECT plaquiste peintre caen';
UPDATE "prospectsPotentiels" SET "reviewCount" = 5, rating = 5.0 WHERE name = 'illiCO travaux';
UPDATE "prospectsPotentiels" SET "reviewCount" = 4, rating = 4.9 WHERE name = 'Brio Decor';
UPDATE "prospectsPotentiels" SET "reviewCount" = 4, rating = 4.8 WHERE name = 'michel rénovations';
UPDATE "prospectsPotentiels" SET "reviewCount" = 4, rating = 4.8 WHERE name = 'LC Rénover Menuiserie';
UPDATE "prospectsPotentiels" SET "reviewCount" = 5, rating = 5.0 WHERE name = 'Husnot Rénovation';
UPDATE "prospectsPotentiels" SET "reviewCount" = 4, rating = 4.9 WHERE name = 'EI. Plessis services';
UPDATE "prospectsPotentiels" SET "reviewCount" = 5, rating = 5.0 WHERE name = 'Roger rénovation';
UPDATE "prospectsPotentiels" SET "reviewCount" = 4, rating = 4.4 WHERE name = 'Lancelin et Fils';
UPDATE "prospectsPotentiels" SET "reviewCount" = 5, rating = 5.0 WHERE name = 'WA Maçonnerie';
UPDATE "prospectsPotentiels" SET "reviewCount" = 5, rating = 5.0 WHERE name = 'Renov Calvados';
UPDATE "prospectsPotentiels" SET "reviewCount" = 4, rating = 4.9 WHERE name = 'Peintre Artisan L'' Atelier de Romy';
UPDATE "prospectsPotentiels" SET "reviewCount" = 4, rating = 4.8 WHERE name = 'Kreit couverture Mouen - couvreur Caen Couvreur Calvados : Réparation Nettoyage Démoussage Dépannage Fuites Toiture 14 Caen';
UPDATE "prospectsPotentiels" SET "reviewCount" = 4, rating = 4.9 WHERE name = 'Déclic Habitat - Isolation extérieure - Fenêtres - Portes d''entrées aluminium K-Line';
UPDATE "prospectsPotentiels" SET "reviewCount" = 5, rating = 5.0 WHERE name = 'Couverture Sellamine';
UPDATE "prospectsPotentiels" SET "reviewCount" = 4, rating = 4.9 WHERE name = 'Anthony Couverture - Couvreur - Caen';
UPDATE "prospectsPotentiels" SET "reviewCount" = 5, rating = 5.0 WHERE name = 'Normandie Bio-Logi''K Construction';
UPDATE "prospectsPotentiels" SET "reviewCount" = 4, rating = 4.9 WHERE name = 'Husnot Couverture';
UPDATE "prospectsPotentiels" SET "reviewCount" = 4, rating = 4.4 WHERE name = '2B Peinture';
UPDATE "prospectsPotentiels" SET "reviewCount" = 5, rating = 5.0 WHERE name = 'Renard Roman - Roman Couverture';
UPDATE "prospectsPotentiels" SET "reviewCount" = 4, rating = 4.4 WHERE name = 'Accrosport Caen';
UPDATE "prospectsPotentiels" SET "reviewCount" = 4, rating = 4.8 WHERE name = 'Atrium - Fitness & Bien-être';
UPDATE "prospectsPotentiels" SET "reviewCount" = 4, rating = 4.7 WHERE name = 'Elancia';
UPDATE "prospectsPotentiels" SET "reviewCount" = 4, rating = 4.4 WHERE name = 'Basic-Fit';
UPDATE "prospectsPotentiels" SET "reviewCount" = 4, rating = 4.8 WHERE name = 'ELANCIA CAEN BEAULIEU';
UPDATE "prospectsPotentiels" SET "reviewCount" = 4, rating = 4.1 WHERE name = 'Basic-Fit 24/7';
UPDATE "prospectsPotentiels" SET "reviewCount" = 5, rating = 5.0 WHERE name = 'À Caen La Forme';
UPDATE "prospectsPotentiels" SET "reviewCount" = 4, rating = 4.2 WHERE name = 'Dark Fitness';
UPDATE "prospectsPotentiels" SET "reviewCount" = 4, rating = 4.2 WHERE name = 'L''Univers de la Forme';
UPDATE "prospectsPotentiels" SET "reviewCount" = 4, rating = 4.9 WHERE name = 'Fit Caen''p';
UPDATE "prospectsPotentiels" SET "reviewCount" = 4, rating = 4.8 WHERE name = 'JLH Sport Santé Caen';
UPDATE "prospectsPotentiels" SET "reviewCount" = 3, rating = 3.9 WHERE name = 'Lady Fitness';
UPDATE "prospectsPotentiels" SET "reviewCount" = 4, rating = 4.8 WHERE name = 'ELANCIA CAEN MONDEVILLE';
UPDATE "prospectsPotentiels" SET "reviewCount" = 5, rating = 5.0 WHERE name = 'All Day training Gym';
UPDATE "prospectsPotentiels" SET "reviewCount" = 5, rating = 5.0 WHERE name = 'STIM''UP CAEN I Studio Electrostimulation Coaching';
UPDATE "prospectsPotentiels" SET "reviewCount" = 5, rating = 5.0 WHERE name = 'Lions Park';
UPDATE "prospectsPotentiels" SET "reviewCount" = 4, rating = 4.7 WHERE name = 'CCHM Caen Calvados Haltérophilie Musculation';
UPDATE "prospectsPotentiels" SET "reviewCount" = 4, rating = 4.4 WHERE name = 'Force Athlétique Caennaise';
UPDATE "prospectsPotentiels" SET "reviewCount" = 4, rating = 4.6 WHERE name = 'VITAL FORME IFS';
UPDATE "prospectsPotentiels" SET "reviewCount" = 4, rating = 4.4 WHERE name = 'L''Orange Bleue';
UPDATE "prospectsPotentiels" SET "reviewCount" = 4, rating = 4.4 WHERE name = 'COSY FORM CAEN : CENTRE DE COACHING SPORTIF - AMINCISSEMENT, AQUABIKING & ELECTROSTIMULATION';
UPDATE "prospectsPotentiels" SET "reviewCount" = 4, rating = 4.9 WHERE name = 'FitnessBoutique Caen';
UPDATE "prospectsPotentiels" SET "reviewCount" = 4, rating = 4.6 WHERE name = 'Planète Fitness - Salle de sport Carpiquet';
UPDATE "prospectsPotentiels" SET "reviewCount" = 4, rating = 4.7 WHERE name = 'Halle sportive Saint Jean Eudes';
UPDATE "prospectsPotentiels" SET "reviewCount" = 4, rating = 4.2 WHERE name = 'L''Orange bleue Mon coach Fitness';
UPDATE "prospectsPotentiels" SET "reviewCount" = 4, rating = 4.2 WHERE name = 'Centre Sportif La Haie Vigné';
UPDATE "prospectsPotentiels" SET "reviewCount" = 5, rating = 5.0 WHERE name = 'BODYHIT EMS CAEN ELECTROSTIMULATION & CRYOLIPOLYSE';
UPDATE "prospectsPotentiels" SET "reviewCount" = 5, rating = 5.0 WHERE name = 'ABLE TRAINING CLUB';
UPDATE "prospectsPotentiels" SET "reviewCount" = 4, rating = 4.5 WHERE name = 'La Butte de Caen';
UPDATE "prospectsPotentiels" SET "reviewCount" = 4, rating = 4.9 WHERE name = 'La salle by Anthony Levionnois';
UPDATE "prospectsPotentiels" SET "reviewCount" = 5, rating = 5.0 WHERE name = 'Club Sport Santé';
UPDATE "prospectsPotentiels" SET "reviewCount" = 4, rating = 4.7 WHERE name = 'District 14';
UPDATE "prospectsPotentiels" SET "reviewCount" = 5, rating = 5.0 WHERE name = 'Secret Naturel';
UPDATE "prospectsPotentiels" SET "reviewCount" = 5, rating = 5.0 WHERE name = 'Le cab'' bien-être - massage - caen';
UPDATE "prospectsPotentiels" SET "reviewCount" = 5, rating = 5.0 WHERE name = 'NATURÉZA massages énergétiques de bien-être';
UPDATE "prospectsPotentiels" SET "reviewCount" = 4, rating = 4.4 WHERE name = 'Le Chamarel Spa';
UPDATE "prospectsPotentiels" SET "reviewCount" = 4, rating = 4.7 WHERE name = 'Zen Hammam';
UPDATE "prospectsPotentiels" SET "reviewCount" = 4, rating = 4.9 WHERE name = 'Zen Jacuzzi';
UPDATE "prospectsPotentiels" SET "reviewCount" = 5, rating = 5.0 WHERE name = 'Tori Bien-être';
UPDATE "prospectsPotentiels" SET "reviewCount" = 5, rating = 5.0 WHERE name = 'Infiniment Head Spa | Head Spa Caen';
UPDATE "prospectsPotentiels" SET "reviewCount" = 4, rating = 4.9 WHERE name = 'Camille.M Abbaye aux Hommes - Institut de Beauté & Massage Caen';
UPDATE "prospectsPotentiels" SET "reviewCount" = 5, rating = 5.0 WHERE name = 'Ismaël — Massage Ayurvédique & Sportif';
UPDATE "prospectsPotentiels" SET "reviewCount" = 5, rating = 5.0 WHERE name = 'HEAD SPA CAEN - NS Spa Chevelure de rêve';
UPDATE "prospectsPotentiels" SET "reviewCount" = 5, rating = 5.0 WHERE name = 'Anthony Monize - Massage Caen';
UPDATE "prospectsPotentiels" SET "reviewCount" = 5, rating = 5.0 WHERE name = 'Chrisalia Bien-être';
UPDATE "prospectsPotentiels" SET "reviewCount" = 4, rating = 4.9 WHERE name = 'Ghaïa Énergie Bien Etre - Massage - Caen';
UPDATE "prospectsPotentiels" SET "reviewCount" = 5, rating = 5.0 WHERE name = 'Ana Massages & bien être';
UPDATE "prospectsPotentiels" SET "reviewCount" = 4, rating = 4.9 WHERE name = 'HARMONIE INSTITUT';
UPDATE "prospectsPotentiels" SET "reviewCount" = 5, rating = 5.0 WHERE name = 'Cocoon Touch';
UPDATE "prospectsPotentiels" SET "reviewCount" = 5, rating = 5.0 WHERE name = 'Renaturessence';
UPDATE "prospectsPotentiels" SET "reviewCount" = 4, rating = 4.5 WHERE name = 'WANG TUINA massages Bien-Être - Caen';
UPDATE "prospectsPotentiels" SET "reviewCount" = 5, rating = 5.0 WHERE name = 'Marie Korna – Institut de massages';
UPDATE "prospectsPotentiels" SET "reviewCount" = 5, rating = 5.0 WHERE name = 'Studio Head Spa | Caen';
UPDATE "prospectsPotentiels" SET "reviewCount" = 5, rating = 5.0 WHERE name = 'BABY SPA BY E';
UPDATE "prospectsPotentiels" SET "reviewCount" = 4, rating = 4.9 WHERE name = 'Mai''be - la Maison du Bien-Etre';
UPDATE "prospectsPotentiels" SET "reviewCount" = 4, rating = 4.8 WHERE name = 'Association "La Bulle du Bien-Etre" à Caen';
UPDATE "prospectsPotentiels" SET "reviewCount" = 5, rating = 5.0 WHERE name = 'La Maison Auraé – Head Spa & Soin profond Caen';
UPDATE "prospectsPotentiels" SET "reviewCount" = 4, rating = 4.7 WHERE name = 'Institut Mélusine Spa et Beauté';
UPDATE "prospectsPotentiels" SET "reviewCount" = 5, rating = 5.0 WHERE name = 'Morgan Spoetler Massage Caen (Sokuatsu - Thaï Nuad Boran - Chi Nei Tsang)';
UPDATE "prospectsPotentiels" SET "reviewCount" = 4, rating = 4.1 WHERE name = 'Venus SAUNA CAEN';
UPDATE "prospectsPotentiels" SET "reviewCount" = 4, rating = 4.9 WHERE name = 'La Clinique du Monde';
UPDATE "prospectsPotentiels" SET "reviewCount" = 4, rating = 4.4 WHERE name = 'BODY BIEN ETRE massage Caen';
UPDATE "prospectsPotentiels" SET "reviewCount" = 5, rating = 5.0 WHERE name = 'Un temps à soi Caen';
UPDATE "prospectsPotentiels" SET "reviewCount" = 5, rating = 5.0 WHERE name = 'Joann Guérardel - Masseur bien être et facialiste';
UPDATE "prospectsPotentiels" SET "reviewCount" = 5, rating = 5.0 WHERE name = 'Morgane Laurent Caen Massage ayurvédique et Kobido pour femme';
UPDATE "prospectsPotentiels" SET "reviewCount" = 5, rating = 5.0 WHERE name = 'Massage Renata By Virginie';
UPDATE "prospectsPotentiels" SET "reviewCount" = 5, rating = 5.0 WHERE name = 'La Galerie Massages';
UPDATE "prospectsPotentiels" SET "reviewCount" = 5, rating = 5.0 WHERE name = 'L''ilessental Diallo Massages Caen';
UPDATE "prospectsPotentiels" SET "reviewCount" = 5, rating = 5.0 WHERE name = 'Christophe Massage Caen';
UPDATE "prospectsPotentiels" SET "reviewCount" = 5, rating = 5.0 WHERE name = 'B-Raw Method - Coach Sportif Personnel';
UPDATE "prospectsPotentiels" SET "reviewCount" = 5, rating = 5.0 WHERE name = 'Will athletic training - coaching sportif et préparation physique Caen';
UPDATE "prospectsPotentiels" SET "reviewCount" = 4, rating = 4.8 WHERE name = 'Franck Seme - Coach sportif';
UPDATE "prospectsPotentiels" SET "reviewCount" = 5, rating = 5.0 WHERE name = 'Coach Sport & Santé à Caen - CAEN SPORT - Le spécialiste de la thérapie sportive à domicile';
UPDATE "prospectsPotentiels" SET "reviewCount" = 5, rating = 5.0 WHERE name = 'My Coach by Ginkgo Caen';
UPDATE "prospectsPotentiels" SET "reviewCount" = 5, rating = 5.0 WHERE name = 'Alice Geffard - Coach Sportif';
UPDATE "prospectsPotentiels" SET "reviewCount" = 4, rating = 4.6 WHERE name = 'RM - Romain Morin - Coaching Sportif Personnalisé';
UPDATE "prospectsPotentiels" SET "reviewCount" = 5, rating = 5.0 WHERE name = 'Sens et Forme';
UPDATE "prospectsPotentiels" SET "reviewCount" = 5, rating = 5.0 WHERE name = 'JHC Sports - Préparateur Physique et Mental';
UPDATE "prospectsPotentiels" SET "reviewCount" = 5, rating = 5.0 WHERE name = 'Coach sportif santé – Estelle BONAFINI';
UPDATE "prospectsPotentiels" SET "reviewCount" = 5, rating = 5.0 WHERE name = 'charline legrand coach sportif à Caen';
UPDATE "prospectsPotentiels" SET "reviewCount" = 5, rating = 5.0 WHERE name = 'Fox Training';
UPDATE "prospectsPotentiels" SET "reviewCount" = 1, rating = 1.0 WHERE name = 'Killian Coach Sportif à Caen';
UPDATE "prospectsPotentiels" SET "reviewCount" = 0, rating = 0.0 WHERE name = 'Capable - Coach sportif santé - Caen';
UPDATE "prospectsPotentiels" SET "reviewCount" = 5, rating = 5.0 WHERE name = 'P-A Giraud - Coach Sportif à domicile Caen';
UPDATE "prospectsPotentiels" SET "reviewCount" = 5, rating = 5.0 WHERE name = 'Be Brave Coaching';
UPDATE "prospectsPotentiels" SET "reviewCount" = 5, rating = 5.0 WHERE name = 'Core performance training';
UPDATE "prospectsPotentiels" SET "reviewCount" = 5, rating = 5.0 WHERE name = 'Adrian Dutertre - Préparateur mental - Hypnose Caen';
UPDATE "prospectsPotentiels" SET "reviewCount" = 5, rating = 5.0 WHERE name = 'CONCEPT COACHING';
UPDATE "prospectsPotentiels" SET "reviewCount" = 5, rating = 5.0 WHERE name = 'BYM Performance';
UPDATE "prospectsPotentiels" SET "reviewCount" = 5, rating = 5.0 WHERE name = 'GregStudioCoaching';
UPDATE "prospectsPotentiels" SET "reviewCount" = 5, rating = 5.0 WHERE name = 'FIT & LOFT Pascal ROSE';
UPDATE "prospectsPotentiels" SET "reviewCount" = 5, rating = 5.0 WHERE name = 'Elysium Personal Training';
UPDATE "prospectsPotentiels" SET "reviewCount" = 4, rating = 4.9 WHERE name = 'C.A.E.N Training';
UPDATE "prospectsPotentiels" SET "reviewCount" = 5, rating = 5.0 WHERE name = 'PETRUS | Poids • Forme • Performance';
UPDATE "prospectsPotentiels" SET "reviewCount" = 5, rating = 5.0 WHERE name = 'Reda MAZOUZ - Diététicien Nutritionniste / Educateur Coach Sportif à Caen';
UPDATE "prospectsPotentiels" SET "reviewCount" = 5, rating = 5.0 WHERE name = 'Adiyoga Studio Caen - Yoga & Pilates';
UPDATE "prospectsPotentiels" SET "reviewCount" = 5, rating = 5.0 WHERE name = 'Studio Inspire - Pilates & Yoga';
UPDATE "prospectsPotentiels" SET "reviewCount" = 5, rating = 5.0 WHERE name = 'Mon Petit Studio';
UPDATE "prospectsPotentiels" SET "reviewCount" = 4, rating = 4.9 WHERE name = 'NOVA | Pilates Reformer';
UPDATE "prospectsPotentiels" SET "reviewCount" = 4, rating = 4.9 WHERE name = 'Les ateliers de Justine Yoga & Yoga Aérien & Danse à Caen';
UPDATE "prospectsPotentiels" SET "reviewCount" = 5, rating = 5.0 WHERE name = 'Pannier Celine';
UPDATE "prospectsPotentiels" SET "reviewCount" = 4, rating = 4.8 WHERE name = 'Studio Maximilien';
UPDATE "prospectsPotentiels" SET "reviewCount" = 5, rating = 5.0 WHERE name = 'Hastings YOGA CAEN et atelier d’artiste';
UPDATE "prospectsPotentiels" SET "reviewCount" = 5, rating = 5.0 WHERE name = 'Juliette Bayeux - Yoga Caen';
UPDATE "prospectsPotentiels" SET "reviewCount" = 4, rating = 4.7 WHERE name = 'CENTRE DE YOGA SRUTHI - Bouillon Marion';
UPDATE "prospectsPotentiels" SET "reviewCount" = 5, rating = 5.0 WHERE name = 'INSTANT YOGA Caen';
UPDATE "prospectsPotentiels" SET "reviewCount" = 5, rating = 5.0 WHERE name = 'LES P''TITS YOGIS';
UPDATE "prospectsPotentiels" SET "reviewCount" = 5, rating = 5.0 WHERE name = 'Nelly Béal';
UPDATE "prospectsPotentiels" SET "reviewCount" = 5, rating = 5.0 WHERE name = 'LUMO Yoga';
UPDATE "prospectsPotentiels" SET "reviewCount" = 4, rating = 4.9 WHERE name = 'MC Studio';
UPDATE "prospectsPotentiels" SET "reviewCount" = 5, rating = 5.0 WHERE name = 'INTO YOGA';
UPDATE "prospectsPotentiels" SET "reviewCount" = 4, rating = 4.9 WHERE name = 'Corps Connect';
UPDATE "prospectsPotentiels" SET "reviewCount" = 4, rating = 4.8 WHERE name = 'PRANA YOGA';
UPDATE "prospectsPotentiels" SET "reviewCount" = 0, rating = 0.0 WHERE name = 'USFC Union Sportive Folie Couvrechef';
UPDATE "prospectsPotentiels" SET "reviewCount" = 3, rating = 3.7 WHERE name = 'Rougier Et Fils';
UPDATE "prospectsPotentiels" SET "reviewCount" = 4, rating = 4.8 WHERE name = 'TRADIBAT NORMANDIE';
UPDATE "prospectsPotentiels" SET "reviewCount" = 4, rating = 4.1 WHERE name = 'SOMTP CAEN';
UPDATE "prospectsPotentiels" SET "reviewCount" = 4, rating = 4.4 WHERE name = 'Elevia Construction';
UPDATE "prospectsPotentiels" SET "reviewCount" = 4, rating = 4.7 WHERE name = 'Maison du Bâtiment';
UPDATE "prospectsPotentiels" SET "reviewCount" = 3, rating = 3.6 WHERE name = 'Eiffage Construction Basse Normandie';
UPDATE "prospectsPotentiels" SET "reviewCount" = 5, rating = 5.0 WHERE name = 'BATIMAT14';
UPDATE "prospectsPotentiels" SET "reviewCount" = 5, rating = 5.0 WHERE name = 'NormandieBat – Maçonnerie & Construction Caen';
UPDATE "prospectsPotentiels" SET "reviewCount" = 4, rating = 4.8 WHERE name = 'Maisons Caen Construction';
UPDATE "prospectsPotentiels" SET "reviewCount" = 4, rating = 4.4 WHERE name = 'ALIA BTP';
UPDATE "prospectsPotentiels" SET "reviewCount" = 4, rating = 4.2 WHERE name = 'SAS AVENIR BTP';
UPDATE "prospectsPotentiels" SET "reviewCount" = 4, rating = 4.4 WHERE name = 'Pmtp';
UPDATE "prospectsPotentiels" SET "reviewCount" = 4, rating = 4.2 WHERE name = 'Caen Travaux';
UPDATE "prospectsPotentiels" SET "reviewCount" = 3, rating = 3.4 WHERE name = 'Visa BTP';
UPDATE "prospectsPotentiels" SET "reviewCount" = 4, rating = 4.5 WHERE name = 'Maisons d''Interieur';
UPDATE "prospectsPotentiels" SET "reviewCount" = 4, rating = 4.4 WHERE name = 'Bâtiment CFA Caen';
UPDATE "prospectsPotentiels" SET "reviewCount" = 5, rating = 5.0 WHERE name = 'EURL LONYBAT';
UPDATE "prospectsPotentiels" SET "reviewCount" = 3, rating = 3.8 WHERE name = 'Guenon TP';
UPDATE "prospectsPotentiels" SET "reviewCount" = 5, rating = 5.0 WHERE name = 'Vivestia';
UPDATE "prospectsPotentiels" SET "reviewCount" = 4, rating = 4.8 WHERE name = 'Sas Carneiro';
UPDATE "prospectsPotentiels" SET "reviewCount" = 4, rating = 4.0 WHERE name = 'Sogéa Nord Ouest T. P.';
UPDATE "prospectsPotentiels" SET "reviewCount" = 5, rating = 5.0 WHERE name = 'Sogea Nord-Ouest';
UPDATE "prospectsPotentiels" SET "reviewCount" = 5, rating = 5.0 WHERE name = 'Ck Btp';
UPDATE "prospectsPotentiels" SET "reviewCount" = 4, rating = 4.0 WHERE name = 'Chesnel Batiment SAS';
UPDATE "prospectsPotentiels" SET "reviewCount" = 5, rating = 5.0 WHERE name = 'Fédération du Bâtiment et des Travaux Publics du Calvados';
UPDATE "prospectsPotentiels" SET "reviewCount" = 4, rating = 4.6 WHERE name = 'Temporis CAEN BTP';
UPDATE "prospectsPotentiels" SET "reviewCount" = 3, rating = 3.9 WHERE name = 'DEFICO';
UPDATE "prospectsPotentiels" SET "reviewCount" = 4, rating = 4.5 WHERE name = 'ABSCIS BERTIN CONSTRUCTION (Direction régionale Normandie - Spie batignolles construction régions)';
UPDATE "prospectsPotentiels" SET "reviewCount" = 4, rating = 4.4 WHERE name = 'Lehodey TP';
UPDATE "prospectsPotentiels" SET "reviewCount" = 5, rating = 5.0 WHERE name = 'Le Charpentier Caennais';
UPDATE "prospectsPotentiels" SET "reviewCount" = 5, rating = 5.0 WHERE name = 'Charpentier Caen - Célestia';
UPDATE "prospectsPotentiels" SET "reviewCount" = 5, rating = 5.0 WHERE name = 'Médéric JEANNE - Charpentier';
UPDATE "prospectsPotentiels" SET "reviewCount" = 3, rating = 3.7 WHERE name = 'Menuiserie Buhour Leconte';
UPDATE "prospectsPotentiels" SET "reviewCount" = 5, rating = 5.0 WHERE name = 'AS Menuiserie-Charpente';
UPDATE "prospectsPotentiels" SET "reviewCount" = 5, rating = 5.0 WHERE name = 'La Bouate';
UPDATE "prospectsPotentiels" SET "reviewCount" = 4, rating = 4.8 WHERE name = 'Menuiserie Mazire';
UPDATE "prospectsPotentiels" SET "reviewCount" = 4, rating = 4.7 WHERE name = 'MDB - Les Métiers du Bois Caen';
UPDATE "prospectsPotentiels" SET "reviewCount" = 5, rating = 5.0 WHERE name = 'CENIER Joris';
UPDATE "prospectsPotentiels" SET "reviewCount" = 5, rating = 5.0 WHERE name = 'All Works';
UPDATE "prospectsPotentiels" SET "reviewCount" = 5, rating = 5.0 WHERE name = 'Damien Thaunay menuisier agenceur';
UPDATE "prospectsPotentiels" SET "reviewCount" = 4, rating = 4.9 WHERE name = 'GM Rénovation Menuiserie A Caen spécialisé dans le Portail alu , Carport et Pergola ,Fenêtres ,Portes d''entrée,Volets.';
UPDATE "prospectsPotentiels" SET "reviewCount" = 5, rating = 5.0 WHERE name = 'Caen Menuiseries Isolations SA';
UPDATE "prospectsPotentiels" SET "reviewCount" = 5, rating = 5.0 WHERE name = 'Les Ateliers Duvernois Caen - Menuiserie - Ebenisterie Sur-Mesure';
UPDATE "prospectsPotentiels" SET "reviewCount" = 4, rating = 4.8 WHERE name = 'Michalcik - Fabricant de menuiseries Technal - Hall d''exposition';
UPDATE "prospectsPotentiels" SET "reviewCount" = 0, rating = 0.0 WHERE name = 'Menuiserie Ebenisterie LEGIONNET Philippe';
UPDATE "prospectsPotentiels" SET "reviewCount" = 5, rating = 5.0 WHERE name = 'Dillée Charpente - Charpentier et Couvreur à Caen dans le Calvados en Normandie';
UPDATE "prospectsPotentiels" SET "reviewCount" = 0, rating = 0.0 WHERE name = 'OB Menuiserie Isolation';
UPDATE "prospectsPotentiels" SET "reviewCount" = 4, rating = 4.8 WHERE name = 'La Boutique du Menuisier Caen';
UPDATE "prospectsPotentiels" SET "reviewCount" = 5, rating = 5.0 WHERE name = 'GuillHard Confort Menuiseries Fenêtres Portes Caen';
UPDATE "prospectsPotentiels" SET "reviewCount" = 4, rating = 4.8 WHERE name = 'Caen Charpente SAS';
UPDATE "prospectsPotentiels" SET "reviewCount" = 4, rating = 4.5 WHERE name = 'Entreprise Menuiserie Caen - SARL DUVERNOIS';
UPDATE "prospectsPotentiels" SET "reviewCount" = 4, rating = 4.9 WHERE name = 'Actibat';
UPDATE "prospectsPotentiels" SET "reviewCount" = 5, rating = 5.0 WHERE name = 'AMC Guérin Menuiserie';
UPDATE "prospectsPotentiels" SET "reviewCount" = 5, rating = 5.0 WHERE name = 'Menuiserie Daigremont';
UPDATE "prospectsPotentiels" SET "reviewCount" = 4, rating = 4.4 WHERE name = 'B''PLAST VIRE';
UPDATE "prospectsPotentiels" SET "reviewCount" = 4, rating = 4.7 WHERE name = 'Menuiserie Agencements Lesort';
UPDATE "prospectsPotentiels" SET "reviewCount" = 4, rating = 4.3 WHERE name = 'Haret Déco';
UPDATE "prospectsPotentiels" SET "reviewCount" = 5, rating = 5.0 WHERE name = 'Artisanat Deperiers - Fenêtres Solabaie Caen';
UPDATE "prospectsPotentiels" SET "reviewCount" = 5, rating = 5.0 WHERE name = 'Arnaud Leriche Menuisierie et Agencement Caen';
UPDATE "prospectsPotentiels" SET "reviewCount" = 4, rating = 4.5 WHERE name = 'Décorisol Caennaise';
UPDATE "prospectsPotentiels" SET "reviewCount" = 4, rating = 4.8 WHERE name = 'Demaisons Menuiserie';
UPDATE "prospectsPotentiels" SET "reviewCount" = 4, rating = 4.2 WHERE name = 'GPAL - Art et Fenêtres Caen';
UPDATE "prospectsPotentiels" SET "reviewCount" = 5, rating = 5.0 WHERE name = 'Levannier menuiserie';
UPDATE "prospectsPotentiels" SET "reviewCount" = 5, rating = 5.0 WHERE name = 'Asdecarreaux LMN carreleur';
UPDATE "prospectsPotentiels" SET "reviewCount" = 5, rating = 5.0 WHERE name = 'Carreleur Caen 14';
UPDATE "prospectsPotentiels" SET "reviewCount" = 5, rating = 5.0 WHERE name = 'Lechevrel Carrelage';
UPDATE "prospectsPotentiels" SET "reviewCount" = 5, rating = 5.0 WHERE name = 'Artisan carreleur à Caen (Normandie)';
UPDATE "prospectsPotentiels" SET "reviewCount" = 5, rating = 5.0 WHERE name = 'KS CREATION CARRELAGE';
UPDATE "prospectsPotentiels" SET "reviewCount" = 5, rating = 5.0 WHERE name = 'Entreprise Piolain Carrelage';
UPDATE "prospectsPotentiels" SET "reviewCount" = 5, rating = 5.0 WHERE name = 'NB Carrelage';
UPDATE "prospectsPotentiels" SET "reviewCount" = 5, rating = 5.0 WHERE name = 'GL Carrelage - Carreleur Caen';
UPDATE "prospectsPotentiels" SET "reviewCount" = 3, rating = 3.8 WHERE name = 'Entreprise Dumaine';
UPDATE "prospectsPotentiels" SET "reviewCount" = 5, rating = 5.0 WHERE name = 'SARL Calvados Carrelage Résine Décorative Maçonnerie';
UPDATE "prospectsPotentiels" SET "reviewCount" = 5, rating = 5.0 WHERE name = 'Pierre Leclerc Peinture - Peinture, papier peint, revêtement sol et mur, ravalement dans le Calvados';
UPDATE "prospectsPotentiels" SET "reviewCount" = 5, rating = 5.0 WHERE name = 'Launay david';
UPDATE "prospectsPotentiels" SET "reviewCount" = 4, rating = 4.7 WHERE name = 'LaRéno Normandie';
UPDATE "prospectsPotentiels" SET "reviewCount" = 3, rating = 3.9 WHERE name = 'NETTO DECOR HABITAT';
UPDATE "prospectsPotentiels" SET "reviewCount" = 3, rating = 3.4 WHERE name = 'Pierre Gras EURL';
UPDATE "prospectsPotentiels" SET "reviewCount" = 5, rating = 5.0 WHERE name = 'Bessin Carrelage';
UPDATE "prospectsPotentiels" SET "reviewCount" = 4, rating = 4.7 WHERE name = 'Let''sCouleurs&Sol';
UPDATE "prospectsPotentiels" SET "reviewCount" = 4, rating = 4.1 WHERE name = 'Gaspin Amenagement';
UPDATE "prospectsPotentiels" SET "reviewCount" = 5, rating = 5.0 WHERE name = 'JC Services – entreprise de rénovation Deauville | Plaquiste Deauville | entreprise de peinture Deauville | carreleur';
UPDATE "prospectsPotentiels" SET "reviewCount" = 5, rating = 5.0 WHERE name = 'Mister Toit';
UPDATE "prospectsPotentiels" SET "reviewCount" = 3, rating = 3.7 WHERE name = 'Entreprise Blondaud Urbin';
UPDATE "prospectsPotentiels" SET "reviewCount" = 5, rating = 5.0 WHERE name = 'Tendance Rénovation 14';
UPDATE "prospectsPotentiels" SET "reviewCount" = 5, rating = 5.0 WHERE name = 'SASU Lelievre Romain';
UPDATE "prospectsPotentiels" SET "reviewCount" = 0, rating = 0.0 WHERE name = 'G.H BAT';