INSERT INTO "prospectsPotentiels" (name, sector, address, city, phone, website, score, "webVisibilityScore", "hasWebsite", "hasActiveWebsite", "hasSocialMedia", status, "createdAt", "updatedAt") VALUES
('Damien Thaunay menuisier agenceur', 'BTP', '71 Bd Général Vanier, 14000 Caen', 'Caen', '06 62 12 57 80', NULL, 75, 75, false, false, false, 'nouveau', NOW(), NOW()),
('GM Rénovation Menuiserie A Caen spécialisé dans le Portail alu , Carport et Pergola ,Fenêtres ,Portes d''entrée,Volets.', 'BTP', '13 Rue Denis Papin, 14120 Mondeville', 'Caen', '02 31 82 17 14', 'https://www.gm-renovation.fr/', 30, 30, true, true, false, 'nouveau', NOW(), NOW()),
('Caen Menuiseries Isolations SA', 'BTP', 'Za Les Portes De La Suisse Normande, 13 Delle du Poirier, 14320 Saint-André-sur-Orne', 'Caen', '02 31 83 85 44', NULL, 75, 75, false, false, false, 'nouveau', NOW(), NOW()),
('Les Ateliers Duvernois Caen - Menuiserie - Ebenisterie Sur-Mesure', 'BTP', '8 Av. du Fresne, 14760 Bretteville-sur-Odon', 'Caen', '02 61 53 52 54', 'https://lesateliersduvernois.fr/', 30, 30, true, true, false, 'nouveau', NOW(), NOW()),
('Michalcik - Fabricant de menuiseries Technal - Hall d''exposition', 'BTP', '522 Av. des Digues, 14123 Fleury-sur-Orne', 'Caen', '02 31 36 21 21', 'https://www.michalcik-caen.fr/', 30, 30, true, true, false, 'nouveau', NOW(), NOW()),
('Menuiserie Ebenisterie LEGIONNET Philippe', 'BTP', '4 bis Rue de la Masse, 14000 Caen', 'Caen', '02 31 93 32 36', NULL, 80, 80, false, false, false, 'nouveau', NOW(), NOW()),
('Dillée Charpente - Charpentier et Couvreur à Caen dans le Calvados en Normandie', 'BTP', '19 Rue Nicéphore Niépce, 14120 Mondeville', 'Caen', '06 82 59 59 28', 'https://www.dillee-charpente.fr/', 30, 30, true, true, false, 'nouveau', NOW(), NOW()),
('OB Menuiserie Isolation', 'BTP', '25 Rue de la Seulles, 14000 Caen', 'Caen', NULL, NULL, 80, 80, false, false, false, 'nouveau', NOW(), NOW()),
('La Boutique du Menuisier Caen', 'BTP', '119 Bd Maréchal Lyautey, 14000 Caen', 'Caen', '06 76 97 83 22', 'https://laboutiquedumenuisier.fr/boutiques/gl-menuiseries', 30, 30, true, true, false, 'nouveau', NOW(), NOW()),
('GuillHard Confort Menuiseries Fenêtres Portes Caen', 'BTP', '2 Rue des Gallois, 14210 Évrecy', 'Caen', '02 31 06 02 23', 'http://caen.guillhardconfort.fr/', 30, 30, true, true, false, 'nouveau', NOW(), NOW()),
('Caen Charpente SAS', 'BTP', '7 Rue Mesaise, 14860 Amfreville', 'Caen', '02 31 78 72 78', 'https://caencharpente.fr/', 30, 30, true, true, false, 'nouveau', NOW(), NOW()),
('Entreprise Menuiserie Caen - SARL DUVERNOIS', 'BTP', NULL, 'Caen', '02 61 53 52 54', 'https://lesateliersduvernois.fr/', 30, 30, true, true, false, 'nouveau', NOW(), NOW()),
('Actibat', 'BTP', '17 All. du Marquis de Hericy, 14740 Saint-Manvieu-Norrey', 'Caen', '09 50 50 13 44', 'https://www.actibat-habitat.fr/?utm_medium=referral&utm_source=gmb&utm_campaign=lnk-gmb', 30, 30, true, true, false, 'nouveau', NOW(), NOW()),
('AMC Guérin Menuiserie', 'BTP', NULL, 'Caen', '02 31 26 52 76', NULL, 75, 75, false, false, false, 'nouveau', NOW(), NOW()),
('Menuiserie Daigremont', 'BTP', 'Imp. le Bourbillon, 14260 Dialan sur Chaîne', 'Caen', '06 48 60 32 85', 'https://menuiseriedaigremont.fr/', 30, 30, true, true, false, 'nouveau', NOW(), NOW()),
('B''PLAST VIRE', 'BTP', 'ZA le maupas, 125 Rue de l''Allière, 14500 Vire Normandie', 'Caen', '02 31 66 25 10', 'https://www.bplast.fr/agences/bplast-vire/?utm_source=GMB&utm_medium=Organique&utm_campaign=GMB+Vire', 30, 30, true, true, false, 'nouveau', NOW(), NOW()),
('Menuiserie Agencements Lesort', 'BTP', '12 Rue Jean Monnet, 14460 Colombelles', 'Caen', '02 31 34 25 15', 'http://www.atelier-lesort.fr/?utm_source=gmb', 30, 30, true, true, false, 'nouveau', NOW(), NOW()),
('Haret Déco', 'BTP', '3 Rue des Entrepreneurs, ZAC de la Grande Plaine, 14760 Bretteville-sur-Odon', 'Caen', '02 31 80 38 02', 'http://www.haretdeco.fr/', 30, 30, true, true, false, 'nouveau', NOW(), NOW()),
('Artisanat Deperiers - Fenêtres Solabaie Caen', 'BTP', '02 Le Château, 14260 Les Monts d''Aunay', 'Caen', '06 14 49 81 19', NULL, 75, 75, false, false, false, 'nouveau', NOW(), NOW()),
('Arnaud Leriche Menuisierie et Agencement Caen', 'BTP', 'ZI Caen Canal, Rue de la Mer, 14550 Blainville-sur-Orne', 'Caen', '06 58 46 16 60', NULL, 75, 75, false, false, false, 'nouveau', NOW(), NOW()),
('Décorisol Caennaise', 'BTP', '222 Av. des Digues, 14123 Fleury-sur-Orne', 'Caen', '02 31 47 45 45', 'https://www.veranda-menuiserie.fr/agence/caen-decorisol-caseo/', 30, 30, true, true, false, 'nouveau', NOW(), NOW()),
('Demaisons Menuiserie', 'BTP', '8 Rue des Hêtres, 14250 Thue et Mue', 'Caen', '06 47 73 38 85', 'http://www.demaisons-menuiserie.fr/', 30, 30, true, true, false, 'nouveau', NOW(), NOW()),
('GPAL - Art et Fenêtres Caen', 'BTP', '6 Bd de l''Espérance, 14123 Cormelles-le-Royal', 'Caen', '02 31 52 49 58', 'https://gpal.artetfenetres.com/', 30, 30, true, true, false, 'nouveau', NOW(), NOW()),
('Levannier menuiserie', 'BTP', NULL, 'Caen', '06 35 19 34 24', NULL, 75, 75, false, false, false, 'nouveau', NOW(), NOW()),
('Asdecarreaux LMN carreleur', 'BTP', '4 Rue Louis Borderieux, 14000 Caen', 'Caen', '06 99 90 89 58', NULL, 75, 75, false, false, false, 'nouveau', NOW(), NOW()),
('Carreleur Caen 14', 'BTP', '11 Rue Guilbert, 14000 Caen', 'Caen', '02 44 22 00 10', 'https://carreleur-caen.com/', 30, 30, true, true, false, 'nouveau', NOW(), NOW()),
('Lechevrel Carrelage', 'BTP', '24 Rue Alexander Fleming, 14200 Hérouville-Saint-Clair', 'Caen', '02 31 47 52 33', 'http://www.lechevrel-carrelage-caen.com/', 30, 30, true, true, false, 'nouveau', NOW(), NOW()),
('Artisan carreleur à Caen (Normandie)', 'BTP', '913 Bd du Bois, 14200 Hérouville-Saint-Clair', 'Caen', '06 68 90 12 06', NULL, 75, 75, false, false, false, 'nouveau', NOW(), NOW()),
('KS CREATION CARRELAGE', 'BTP', 'Zac Lazzaro, 3 Rue du Four à Chaux 3, 14460 Colombelles', 'Caen', '02 31 22 33 76', 'http://www.kscreationcarrelage.fr/', 30, 30, true, true, false, 'nouveau', NOW(), NOW()),
('Entreprise Piolain Carrelage', 'BTP', '11 All. Georges Cuvier, 14740 Saint-Manvieu-Norrey', 'Caen', '02 31 25 21 95', 'http://www.piolain-carrelage.fr/', 30, 30, true, true, false, 'nouveau', NOW(), NOW()),
('NB Carrelage', 'BTP', NULL, 'Caen', '06 59 08 84 47', NULL, 75, 75, false, false, false, 'nouveau', NOW(), NOW()),
('GL Carrelage - Carreleur Caen', 'BTP', NULL, 'Caen', '06 70 43 41 74', NULL, 75, 75, false, false, false, 'nouveau', NOW(), NOW()),
('Entreprise Dumaine', 'BTP', NULL, 'Caen', '06 16 38 22 91', NULL, 75, 75, false, false, false, 'nouveau', NOW(), NOW()),
('SARL Calvados Carrelage Résine Décorative Maçonnerie', 'BTP', '110, 14220 Les Moutiers-en-Cinglais', 'Caen', '06 26 40 21 23', 'http://www.calvadoscarrelage.fr/', 30, 30, true, true, false, 'nouveau', NOW(), NOW()),
('Pierre Leclerc Peinture - Peinture, papier peint, revêtement sol et mur, ravalement dans le Calvados', 'BTP', '17, Rue des Pallières ZAC du Cingal, 14680 Bretteville-sur-Laize', 'Caen', '06 35 17 48 17', 'http://www.leclerc-peintre-caen.fr/', 30, 30, true, true, false, 'nouveau', NOW(), NOW()),
('Launay david', 'BTP', '28 Rue de Bayeux, 14740 Thue et Mue', 'Caen', '06 62 21 06 53', NULL, 75, 75, false, false, false, 'nouveau', NOW(), NOW()),
('LaRéno Normandie', 'BTP', '8 Rue de Provence, 14440 Douvres-la-Délivrande', 'Caen', '02 90 89 10 95', 'http://lareno14.fr/', 30, 30, true, true, false, 'nouveau', NOW(), NOW()),
('NETTO DECOR HABITAT', 'BTP', '2 Rue des Tisserands, 14123 Ifs', 'Caen', '02 31 72 08 91', 'http://www.netto-decor-habitat.com/', 30, 30, true, true, false, 'nouveau', NOW(), NOW()),
('Pierre Gras EURL', 'BTP', '3 Rue des 4 Vents, 14790 Verson', 'Caen', '02 31 80 87 70', NULL, 80, 80, false, false, false, 'nouveau', NOW(), NOW()),
('Bessin Carrelage', 'BTP', '2 Rue de Guerville, 14740 Rots', 'Caen', '06 15 11 57 23', 'https://www.bessin-carrelage.fr/', 30, 30, true, true, false, 'nouveau', NOW(), NOW());